language: ruby
cache: bundler
rvm:
    - 2.4.0
services:
    - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - psql -c 'create database advancements_react_test' -U postgres
script:
    - bundle exec rake db:test:prepare
    - bundle exec rspec spec/
