users = [
  {'email' => 'user@user.com', 'password' => 'password'}
]

meritbadges = [
{'name' => 'American Business'},
{'name' => 'American Cultures'},
{'name' => 'American Heritage'},
{'name' => 'American Labor'},
{'name' => 'Animal Science'},
{'name' => 'Animation'},
{'name' => 'Archaeology'},
{'name' => 'Archery'},
{'name' => 'Architecture'},
{'name' => 'Art'},
{'name' => 'Astronomy'},
{'name' => 'Athletics'},
{'name' => 'Automotive Maintenance'},
{'name' => 'Aviation'},
{'name' => 'Backpacking'},
{'name' => 'Basketry'},
{'name' => 'Bird Study'},
{'name' => 'Bugling'},
{'name' => 'Camping', 'required' => true},
{'name' => 'Canoeing'},
{'name' => 'Chemistry'},
{'name' => 'Chess'},
{'name' => 'Citizenship in the Community', 'required' => true},
{'name' => 'Citizenship in the Nation', 'required' => true},
{'name' => 'Citizenship in the World', 'required' => true},
{'name' => 'Climbing'},
{'name' => 'Coin Collecting'},
{'name' => 'Collections'},
{'name' => 'Communication', 'required' => true},
{'name' => 'Composite Materials'},
{'name' => 'Cooking', 'required' => true},
{'name' => 'Crime Prevention'},
{'name' => 'Cycling', 'required' => true},
{'name' => 'Dentistry'},
{'name' => 'Digital Technology'},
{'name' => 'Disabilities Awareness'},
{'name' => 'Dog Care'},
{'name' => 'Drafting'},
{'name' => 'Electricity'},
{'name' => 'Electronics'},
{'name' => 'Emergency Preparedness', 'required' => true},
{'name' => 'Energy'},
{'name' => 'Engineering'},
{'name' => 'Entrepreneurship'},
{'name' => 'Environmental Science', 'required' => true},
{'name' => 'Exploration'},
{'name' => 'Family Life', 'required' => true},
{'name' => 'Farm Mechanics'},
{'name' => 'Fingerprinting'},
{'name' => 'Fire Safety'},
{'name' => 'First Aid', 'required' => true},
{'name' => 'Fish and Wildlife Management'},
{'name' => 'Fishing'},
{'name' => 'Fly Fishing'},
{'name' => 'Forestry'},
{'name' => 'Game Design'},
{'name' => 'Gardening'},
{'name' => 'Genealogy'},
{'name' => 'Geocaching'},
{'name' => 'Geology'},
{'name' => 'Golf'},
{'name' => 'Graphic Arts'},
{'name' => 'Hiking', 'required' => true},
{'name' => 'Home Repairs'},
{'name' => 'Horsemanship'},
{'name' => 'Indian Lore'},
{'name' => 'Insect Study'},
{'name' => 'Inventing'},
{'name' => 'Journalism'},
{'name' => 'Kayaking'},
{'name' => 'Landscape Architecture'},
{'name' => 'Law'},
{'name' => 'Leatherwork'},
{'name' => 'Lifesaving', 'required' => true},
{'name' => 'Mammal Study'},
{'name' => 'Medicine'},
{'name' => 'Metalwork'},
{'name' => 'Mining in Society'},
{'name' => 'Model Design and Building'},
{'name' => 'Motorboating'},
{'name' => 'Moviemaking'},
{'name' => 'Music'},
{'name' => 'Nature'},
{'name' => 'Nuclear Science'},
{'name' => 'Oceanography'},
{'name' => 'Orienteering'},
{'name' => 'Painting'},
{'name' => 'Personal Fitness', 'required' => true},
{'name' => 'Personal Management', 'required' => true},
{'name' => 'Pets'},
{'name' => 'Photography'},
{'name' => 'Pioneering'},
{'name' => 'Plant Science'},
{'name' => 'Plumbing'},
{'name' => 'Pottery'},
{'name' => 'Programming'},
{'name' => 'Public Health'},
{'name' => 'Public Speaking'},
{'name' => 'Pulp and Paper'},
{'name' => 'Radio'},
{'name' => 'Railroading'},
{'name' => 'Reading'},
{'name' => 'Reptile and Amphibian Study'},
{'name' => 'Rifle Shooting'},
{'name' => 'Robotics'},
{'name' => 'Rowing'},
{'name' => 'Safety'},
{'name' => 'Salesmanship'},
{'name' => 'Scholarship'},
{'name' => 'Scouting Heritage'},
{'name' => 'Scuba Diving'},
{'name' => 'Sculpture'},
{'name' => 'Search and Rescue'},
{'name' => 'Shotgun Shooting'},
{'name' => 'Signs, Signals, and Codes'},
{'name' => 'Skating'},
{'name' => 'Small-Boat Sailing'},
{'name' => 'Snow Sports'},
{'name' => 'Soil and Water Conservation'},
{'name' => 'Space Exploration'},
{'name' => 'Sports'},
{'name' => 'Stamp Collecting'},
{'name' => 'Surveying'},
{'name' => 'Sustainability', 'required' => true},
{'name' => 'Swimming', 'required' => true},
{'name' => 'Textile'},
{'name' => 'Theater'},
{'name' => 'Traffic Safety'},
{'name' => 'Truck Transportation'},
{'name' => 'Veterinary Medicine'},
{'name' => 'Water Sports'},
{'name' => 'Weather'},
{'name' => 'Welding'},
{'name' => 'Whitewater'},
{'name' => 'Wilderness Survival'},
{'name' => 'Wood Carving'},
{'name' => 'Woodwork'}
]

users.each do |user|
  User.create(user)
end

meritbadges.each do |meritbadge|
  MeritBadge.create(meritbadge)
end
